### ISSUE TITLE
explorer.exe crashes cause FancyWM to crash

### ISSUE THREAD

**Issue by mataslib** [FancyWM/fancywm-issues#31]
**Describe the bug**
Fancy crashes often with error "explorer.exe just crashed and this caused virtual desktops...". It always happens in win+tab mode, eg. when dragging app to another vir. desktop. Dragging chrome with 50 tabs is 100% crash. Seems like windows issue though, weird behaviour (like explorer.exe indeed does crash) happens even without Fancy running :/.

**To Reproduce**
1. Chrome, ctrl+t 50 new tabs
2. Win+tab, drag chrome to another vir. desktop
3. Error 

**Desktop (please complete the following information):**
Device name	mataslib
Processor	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz   2.21 GHz
Installed RAM	64,0 GB (63,7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

Edition	Windows 11 Pro
Version	21H2
Installed on	‎09.‎11.‎2021
OS build	22000.469
Experience	Windows Feature Experience Pack 1000.22000.469.0

**Comment by mataslib** [comment]
@veselink1 Just letting you know I did report issue to Microsoft via feedbackhub. Let's hope it won't take yrs

**Comment by veselink1** [comment]
@mataslib Thanks for reporting to Microsoft. 

This is in fact caused by explorer.exe crashing. When not running, the virtual desktop service is unavailable, so FancyWM has no way of knowing which windows belong to which virtual desktop.

I plan to improve the error handling system, by allowing the user to force the application to continue running, ignoring any errors, but this will likely not be implemented anytime soon.

**Comment by mataslib** [comment]
just leaving here feedback hub link https://aka.ms/AAfkv1q for upvote.

**Comment by veselink1** [comment]
Explorer crashes no longer crash FancyWM as of v2.6.0 in Store now (as long as explorer starts again in 10s).

**Comment by mataslib** [comment]
couldn't test it since explorer stopped crashing in my case
